- import_tasks: configure.yml
  tags: configure
- import_tasks: software.yml
  tags: software
- import_tasks: security.yml
  tags: security
- import_tasks: swap.yml
  tags: swap
  when: swapfile_size != ""