- name: Ensure sudoers.d is enabled
  lineinfile:
    dest: /etc/sudoers
    regexp: '^#includedir /etc/sudoers.d'
    line: '#includedir /etc/sudoers.d'
    state: present
    backup: yes

- name: Set up password-less sudo for admin users
  copy:
    content: "%{{ admin_group }} ALL=(ALL) NOPASSWD:ALL\nDefaults    env_keep+=SSH_AUTH_SOCK\n"
    dest: /etc/sudoers.d/admin
    owner: root
    group: root
    mode: 0440

- name: Strict SSH access
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^#?{{ item.key }}'
    line: '{{ item.key }} {{ item.value }}'
    validate: '/usr/sbin/sshd -t -f %s'
  with_items:
  - { key: 'PermitRootLogin',        value: 'without-password'}
  - { key: 'PasswordAuthentication', value: 'no'}
  - { key: 'AllowGroups',            value: admin_group }
  - { key: 'MaxAuthTries',           value: "5"}
  - { key: 'LoginGraceTime',         value: "60"}
  - { key: 'MaxSessions',            value: "5"}
  - { key: 'MaxStartups',            value: "10:30:60"}
  - { key: 'Port',                   value: '22' }
  notify: Restart sshd

- name: Configure firewall for SSH
  ufw: rule=allow port=22

- name: Enable firewall
  ufw: state=enabled