- name: Set up password-less sudo for sudo group
  lineinfile:
    state: present
    dest: /etc/sudoers
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: root
    group: root
    mode: 0440
  with_items:
  - { regexp: '^#?%sudo\s', line: '%sudo ALL=(ALL) NOPASSWD:ALL'}
  - { regexp: '^Defaults\s*env_keep\+=', line: 'Defaults env_keep+=SSH_AUTH_SOCK'}

- name: Strict SSH access
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^#?{{ item.key }}'
    line: '{{ item.key }} {{ item.value }}'
    validate: '/usr/sbin/sshd -t -f %s'
  with_items:
  - { key: 'PermitRootLogin',        value: 'without-password'}
  - { key: 'PasswordAuthentication', value: 'no'}
  - { key: 'MaxAuthTries',           value: "5"}
  - { key: 'LoginGraceTime',         value: "60"}
  - { key: 'MaxSessions',            value: "5"}
  - { key: 'MaxStartups',            value: "10:30:60"}
  - { key: 'Port',                   value: '22' }
  notify: Restart sshd

- name: Configure firewall for SSH
  ufw: rule=allow port=22

- name: Enable firewall
  ufw: state=enabled