- name: Update APT once in a while
  apt: cache_valid_time=3600 update_cache=yes

- name: Install updates
  apt: upgrade=dist

- name: Install essential packages
  apt: pkg="{{ item }}" state=latest
  with_items:
  - python3
  - python3-pip
  - apt-transport-https
  - ntp
  - fail2ban
  - ufw
  - vim
  - curl

- name: Install essential python packages
  pip: name="{{ item }}" state=latest
  with_items:
  - pip
  - setuptools
  - wheel

- name: Ensure services is running and enabled
  service: name="{{ item }}" state=started enabled=yes
  with_items:
  - ntp
  - fail2ban
